import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/ui/toogle"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const logout = async () => {
  try {
      await axios.get('/api/users/logout');
      router.push('/login')
  } catch (error) {
      console.log(error.message)
      
  }

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <body
        // className={cn(
        //   "min-h-screen bg-background font-sans antialiased",
        //   fontSans.variable
        // )}
      >
                  {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
            <div className="flex justify-end p-3">
            {/* <ModeToggle /> */}
            </div>
        {children}
          {/* </ThemeProvider> */}
        </body>
    </html>
  );
}
